# Generated by Django 5.1.5 on 2025-04-17 07:45

from django.db import migrations

def create_sunny_bites(apps, schema_editor):
    """
    Creates a sample restaurant called 'Sunny Bites' and adds related info and social media.
    """
    Restaurant = apps.get_model('restaurants', 'Restaurant')
    RestaurantInfo = apps.get_model('restaurants', 'RestaurantInfo')
    SocialMedia = apps.get_model('restaurants', 'SocialMedia')

    # Create the 'Sunny Bites' restaurant
    sunny_bites = Restaurant.objects.create(
        name='Sunny Bites',
        slug='sunny-bites',
    )

    # Add detailed information for 'Sunny Bites'
    RestaurantInfo.objects.create(
        restaurant=sunny_bites,
        description='Delicious meals made with fresh ingredients.',
        address='123 Sunny Street, Beach City',
        phone_number='+1 234 567 8901',
        email='contact@sunnybites.com',
        opening_hours='Mon-Fri: 9:00 AM - 9:00 PM',
        currency='EUR',
    )

    # Create SocialMedia entries for 'Sunny Bites'
    SocialMedia.objects.create(
        platform_name='Instagram',
        username='sunnybites',  
        restaurant=sunny_bites
    )
    SocialMedia.objects.create(
        platform_name='Facebook',
        username='sunnybites',  
        restaurant=sunny_bites
    )
    SocialMedia.objects.create(
        platform_name='TikTok',
        username='sunnybites',  
        restaurant=sunny_bites
    )


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sunny_bites),
    ]
