# Generated by Django 5.1.5 on 2025-02-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantinfo',
            options={'verbose_name_plural': 'Restaurants info'},
        ),
    ]
