# Generated by Django 5.1.5 on 2025-04-23 15:15

import django.db.models.deletion
import menus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0003_populate_languages'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=menus.models.dish_photo_upload_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Menu', max_length=200)),
                ('slug', models.SlugField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.language')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'language', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menus.menu')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('menu', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='menus.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menus.category')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='menus.dishbase')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menus.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Languages',
                'constraints': [models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'slug'), name='unique_category_slug'), models.UniqueConstraint(condition=models.Q(('subcategory__isnull', False)), fields=('subcategory', 'slug'), name='unique_subcategory_slug')],
            },
        ),
    ]
