# Generated by Django 5.1.5 on 2025-02-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_alter_category_options_alter_dish_options_and_more'),
        ('restaurants', '0003_add_example_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='extra',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('menu', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='extra',
            unique_together={('restaurant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('restaurant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('category', 'slug'), name='unique_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.UniqueConstraint(condition=models.Q(('subcategory__isnull', False)), fields=('subcategory', 'slug'), name='unique_subcategory_slug'),
        ),
    ]
