# Generated by Django 5.1.5 on 2025-04-23 11:05

import django.db.models.deletion
from django.db import migrations, models

def assign_restaurant_to_dishbase(apps, schema_editor):
    DishBase = apps.get_model('menus', 'DishBase')
    Restaurant = apps.get_model('restaurants', 'Restaurant')

    # Aquí definimos el restaurante que queremos asignar (puedes cambiarlo si es necesario)
    default_restaurant = Restaurant.objects.first()  # Aquí puedes usar cualquier lógica para seleccionar el restaurante

    for dishbase in DishBase.objects.all():
        dishbase.restaurant = default_restaurant
        dishbase.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menus_example_data'),
        ('restaurants', '0002_restaurant_example_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishbase',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
        migrations.RunPython(assign_restaurant_to_dishbase),
    ]
