# Generated by Django 5.1.5 on 2025-04-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_populate_languages'),
        ('menus', '0005_alter_category_menu_alter_dish_category_and_more'),
        ('restaurants', '0004_restaurantinfo_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('restaurant', 'language', 'slug')},
        ),
    ]
